/**
 * @file Demo模块路由定义
 * @author JunBin.Yang
 */
export class DemoRoutes {
  /**
   * Network Demo 示例页路由
   */
  static NetworkDemo = "demo/network-demo";
  /**
   * Network List Demo 示例页路由
   */
  static NetworkListDemo = "demo/network-list-demo";
  /**
   * 数据库示例页路由
   */
  static Database = "demo/database";
  /**
   * 本地存储示例页路由
   */
  static LocalStorage = "demo/local-storage";
  /**
   * 状态管理示例页路由
   */
  static StateManagement = "demo/state-management";
  /**
   * 通用网络请求示例页路由
   */
  static NetworkRequest = "demo/network-request";
  /**
   * 带参跳转示例页路由
   */
  static NavigationWithArgs = "demo/navigation-with-args";
  /**
   * 结果回传示例页路由
   */
  static NavigationResult = "demo/navigation-result";
  /**
   * 安全区示例页路由
   */
  static SafeAreaDemo = "demo/safe-area-demo";
  /**
   * 屏幕适配示例页路由
   */
  static ScreenAdaptDemo = "demo/screen-adapt-demo";
}
